[package]
name = "hutton32-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12"
egui = { git =  "https://github.com/emilk/egui", rev = "940b896c" }
egui-wgpu = { git =  "https://github.com/emilk/egui", rev = "940b896c" }
eframe = { git = "https://github.com/emilk/egui", rev = "940b896c", features = ["wgpu"] }
# egui_gpu_plot = { path = "src/egui_gpu_plot" }
wgpu = "0.14"