[package]
name = "hutton32-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14"
bytemuck = "1.12"
futures-intrusive = "0.5"
pollster = "0.2"

eframe = { version = "0.19.0" }
tracing = "0.1"
tracing-subscriber = "0.3.16"

image = { version = "0.24.4", default-features = false }
imageproc = { version = "0.23.0", default-features = false }

[profile.dev]
incremental = true